### ISSUE TITLE
Misaligned Docs on Zen Browser

### ISSUE THREAD

**Issue by Z-xus** [zen-browser/docs#17]
**Describe the bug**
<html> tag seems to have inadequate `height` but only on zen browser, not on firefox.

**To Reproduce**

1. Go to 'https://docs.zen-browser.app/' with Zen Browser
2. See error

**Expected behavior**
Look the same as firefox.

**Screenshots and Source**
Zen Browser
![image](https://github.com/user-attachments/assets/05d7f534-f419-4c42-b5bd-fce72f0ffeca)

Firefox
![image](https://github.com/user-attachments/assets/f53bb5df-60ad-40ae-bca4-566f0d46ec06)

**Comment by mauro-balades** [comment]
What seems to be the problem exactly? I think it looks fine

**Comment by Z-xus** [comment]
page looks like it cut off from the between and a bit glitchy too

**Comment by Z-xus** [comment]
Sorry for taking your time, The issue is not reproducing anymore and it looks all good now
