### ISSUE TITLE
i18n for docs with vitepress

### ISSUE THREAD

**Issue by imfenghuang** [zen-browser/docs#20]
The docs maybe need i18n, but current `Quartz` may be not easy to support it. 

I tried with `vitepress` and there is a demo `https://github.com/imfenghuang/docs/tree/vitepress`

```js
pnpm install 
pnpm run docs:dev
```
![image](https://github.com/user-attachments/assets/b2560a72-2278-4e97-ae4e-43b1562ba204)
![image](https://github.com/user-attachments/assets/2f2a181d-ba31-4409-9991-fd1371a00e8d)
![image](https://github.com/user-attachments/assets/d6413d8d-3ff7-4333-835c-a679a7dd5177)

**Comment by IAmJafeth** [comment]
Hi @imfenghuang ,

This is a very good suggestion, for the moment we will stick to Quartz an maintain the documentation mainly in English.
We can look forward to i18n support in the future.

I will mark this issue as not planned for the moment.

**Comment by imfenghuang** [comment]
> Hi @imfenghuang ,
> 
> This is a very good suggestion, for the moment we will stick to Quartz an maintain the documentation mainly in English. We can look forward to i18n support in the future.
> 
> I will mark this issue as not planned for the moment.

ok. I will continue translating the documentation once it is stable.
