### ISSUE TITLE
Fix Live Editing Zen Theme docs

### ISSUE THREAD

**Issue by ch4og** [zen-browser/docs#24]
Since https://github.com/zen-browser/desktop/issues/927 was merged starting from a.31 you won't be able to use Ctrl+Shift+Alt+I to open browser toolbox. First you will need to enable remote debugging (https://firefox-source-docs.mozilla.org/devtools-user/browser_toolbox/index.html)

**Comment by IAmJafeth** [comment]
Fixed: ca872e29c568f487e841519cd46c434d703afd0a
