### ISSUE TITLE
Not Portable with params

### ISSUE THREAD

**Issue by truefriend-cz** [zen-browser/docs#27]
### What happened?

On webpage:
https://docs.zen-browser.app/guides/portable
is how to portable mode.
But, if i add param "-P" nothing portable...
Profile folder created in %AppData%

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

1.0.0

### Severity impact

Critical

### What platform are you seeing the problem on?

Windows

**Comment by mauro-balades** [comment]
@IAmJafeth you've got this?

**Comment by NOCanoa** [comment]
@IAmJafeth

**Comment by IAmJafeth** [comment]
Don't have a Windows machine right now, I can build a VM for testing it later

However, please note this guide is an unofficial/unsupported way to make Zen Browser installer portable.

Please use Zen's Windows portable version in the meantime  https://docs.zen-browser.app/guides/downloads

Based on my findings, I will update this guide accordingly 

> [!NOTE]
> ETA: 24 hours

**Comment by IAmJafeth** [comment]
Closed with commit 573537a102f8abd1dd2ccaba508d5e31d8a3c648
