### ISSUE TITLE
Logins do not work when using special characters

### ISSUE THREAD

**Issue by factor3** [zen-browser/docs#59]
**Describe the bug**
If I log into a website whose password contains special characters, the login fails

**To Reproduce**

1. Select a website that requires a login. Make sure the password has characters like '_' or '@' in it
2.Enter your username and password
3. Go to another browser (like Chrome or Firefox), go to the same URL and enter the username and password

**Expected behavior**
You should be logged in to the site (in Zen) as well as in the (for example) Firefox browser

**Actual Behavior**
In Zen: You get a login failure -- even if you put in the correct password
In Firefox: You get logged in

**Comment by NOCanoa** [comment]
this is the docs repo here is the browser https://github.com/zen-browser/desktop repo

**Comment by factor3** [comment]
1. This is not the docs request. This is a bug report. Please reread it.

Here I am talking about how the Zen browser fails to log in to sites that have passwords with special characters. This is a serious *bug*, not a request for docs.

2. There is nothing in the docs repo that talks about how to deal with this *bug*.

**Comment by NOCanoa** [comment]
> 1. This is not the docs request. This is a bug report. Please reread it.
> 
> 
> Here I am talking about how the Zen browser fails to log in to sites that have passwords with special characters. This is a serious _bug_, not a request for docs.
> 
>     2. There is nothing in the docs repo that talks about how to deal with this _bug_.


## Didnt even know this is a bug,
i sent u the Desktop repo where issues related to the browser are,
this repo is just if somting is rithen wrong in the docs or any info that should be aded.
