### ISSUE TITLE
Logins STILL do not work when using special characters

### ISSUE THREAD

**Issue by factor3** [zen-browser/docs#63]
**Describe the bug**
If I log into a website whose password contains special characters, the login fails

**To Reproduce**

1. Select a website that requires a login. Make sure the password has characters like '_' or '@' in it
2.Enter your username and password
3. Go to another browser (like Chrome or Firefox), go to the same URL and enter the username and password

**Expected behavior**
You should be logged in to the site (in Zen) as well as in the (for example) Firefox browser

**Actual Behavior**
In Zen: You get a login failure -- even if you put in the correct password
In Firefox: You get logged in

**Other Info**
NOCanoa: your "solution" to Issue #59 does not help. There is nothing in the documentation to reference this problem or how to deal with it. Please do not close this again until you provide an actual solution to this problem.

**Comment by NOCanoa** [comment]
# Nobody knew this was a bug, I sent u the browser repo that where the dev look at the issues and fix stuff!!

**Comment by NOCanoa** [comment]
ping me in discord

**Comment by cheeeebs** [comment]
Please open an issue here instead: https://github.com/zen-browser/desktop/issues

This is not the right repo for the browser code, this is only for documentation.

**Comment by darkvergus** [comment]
This is ![image](https://github.com/user-attachments/assets/580b4e7d-9e86-410f-ad4e-b69dad3095f9)

its meant to be for documentation, this is an issue related to the browser itself so open in the url provided by @cheeeebs
